services:
  gravitylan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GravityLAN
    restart: always
    cap_add:
      - NET_RAW
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - DOCKER_HOST_IP=192.168.100.37
      - GRAVITYLAN_PORT=8000
    networks:
      gravitylan_net:
        ipv4_address: 192.168.100.254
    volumes:
      - ./data:/app/data

networks:
  gravitylan_net:
    driver: macvlan
    driver_opts:
      parent: ens19
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
