services:
  gravitylan:
    image: sleeperxr/gravitylan:latest
    container_name: GravityLAN
    restart: unless-stopped
    ports:
      - "8000:8000"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./data:/app/data
    environment:
      - TZ=UTC
      - GRAVITYLAN_DEBUG=false
